[package]

name = "time"
version = "0.1.29"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/time"
repository = "https://github.com/rust-lang/time"
documentation = "http://doc.rust-lang.org/time"
description = """
Utilities for working with time-related functions in Rust.
"""

[dependencies]
libc = "0.1"
winapi = "0.1.23"
kernel32-sys = "0.1.2"
rustc-serialize = { version = "0.3", optional = true }

[dev-dependencies]
log = "0.3"
advapi32-sys = "0.1"
