[workspace]
members = ["time-macros"]

[package]
name = "time"
version = "0.3.0-dev"
authors = ["Jacob Pratt <open-source@jhpratt.dev>", "Time contributors"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration", "parser", "formatter", "no_std", "macro"]
categories = ["date-and-time", "no-std", "parser-implementations", "value-formatting"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."
include = ["src/**/*", "LICENSE-*", "README.md", "!src/tests.rs"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "__time_03_docs"]

[features]
default = ["std"]
alloc = []
formatting = ["itoa", "std"]
large-dates = ["time-macros/large-dates"] # use case for weak feature dependencies (rust-lang/cargo#8832)
local-offset = ["std", "winapi"]
macros = ["time-macros"]
parsing = []
quickcheck = ["quickcheck-dep", "alloc"]
serde-human-readable = ["serde", "formatting", "parsing"]
std = ["alloc"]

[dependencies]
const_fn = "0.4.5"
itoa = { version = "0.4.7", optional = true }
quickcheck-dep = { package = "quickcheck", version = "1.0.3", default-features = false, optional = true }
rand = { version = "0.8.3", optional = true, default-features = false }
serde = { version = "1.0.123", optional = true, default-features = false }
standback = { version = "0.3.1", default-features = false, features = ["msrv-1-46"] }
time-macros = { version = "=0.2.0-dev", path = "time-macros", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwinbase", "minwindef", "timezoneapi"], optional = true }

[target.'cfg(unsound_local_offset)'.dependencies]
libc = "0.2.85"

[dev-dependencies]
criterion = { version = "0.3.4", features = ["html_reports"] }
rand = { version = "0.8.3", default-features = false }
serde = { version = "1.0.123", default-features = false }
serde_json = "1.0.61"
serde_test = "1.0.123"

# Significant contributions to the benchmarks provided by Emil Lundberg.
[[bench]]
name = "benchmarks"
harness = false
path = "benchmarks/main.rs"
