[package]
name = "time"
version = "0.2.2"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration"]
categories = ["date-and-time"]
readme = "README.md"
license = "MIT OR Apache-2.0"
# TODO Add GitHub Actions badge once rust-lang/crates.io#1838 is merged.
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."

[features]
default = ["std", "deprecated"]
deprecated = []
std = []
panicking-api = []

[dependencies]
serde = { version = "1", optional = true, default-features = false, features = ["derive", "alloc"] }
time-macros = { version = "0.1", path = "time-macros" }

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [
    "time-macros",
    "time-macros-impl",
]
