[package]
name = "time"
version = "0.3.0-dev"
authors = ["Jacob Pratt <open-source@jhpratt.dev>", "Time contributors"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration"]
categories = ["date-and-time"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustc-args = ["--cfg",  "__time_03_docs"]
rustdoc-args = ["--cfg", "__time_03_docs"]

[features]
default = ["std"]
macros = ["time-macros"]
local-offset = ["std", "libc", "winapi"]
quickcheck = ["quickcheck-dep", "rand", "std"]
std = ["alloc"]
alloc = []

[dependencies]
const_fn = "0.4.3"
quickcheck-dep = { package = "quickcheck", version = "0.9.2", optional = true }
rand = { version = "0.7.3", optional = true, default-features = false }
serde = { version = "1.0.117", optional = true, default-features = false, features = ["derive"] }
time-macros = { version = "=0.2.0-dev", path = "time-macros", optional = true }

[workspace]
members = ["time-benchmarks", "time-macros", "time-macros-impl"]

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.80", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwinbase", "minwindef", "timezoneapi"], optional = true }

[dev-dependencies]
rand = { version = "0.7.3", default-features = false }
serde_json = "1.0.59"
time-macros = { path = "time-macros" }
