name = "Afrikaans"
iso_code = "af"
months = [
    "Januarie",
    "Februarie",
    "Maart",
    "April",
    "Mei",
    "Junie",
    "Julie",
    "Augustus",
    "September",
    "Oktober",
    "November",
    "Desember",
]
abbr_months = [
    "Jan",
    "Feb",
    "Mrt",
    "Apr",
    "Mei",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Okt",
    "Nov",
    "Des",
]
weekdays = [
    "Maandag",
    "Dinsdag",
    "Woensdag",
    "Donderdag",
    "Vrydag",
    "Saterdag",
    "Sondag",
]
abbr_weekdays = [
    "Ma",
    "Di",
    "Wo",
    "Do",
    "Vr",
    "Sa",
    "So",
]
