name = "Albanian"
iso_code = "sq"
months = [
    "janar",
    "shkurt",
    "mars",
    "prill",
    "maj",
    "qershor",
    "korrik",
    "gusht",
    "shtator",
    "tetor",
    "nëntor",
    "dhjetor",
]
abbr_months = [
    "Jan",
    "Shk",
    "Mar",
    "Pri",
    "Maj",
    "Qer",
    "Kor",
    "Gsh",
    "Sht",
    "Tet",
    "Nën",
    "Dhj",
]
weekdays = [
    "e hënë",
    "e martë",
    "e mërkurë",
    "e enjte",
    "e premte",
    "e shtunë",
    "e diel",
]
abbr_weekdays = [
    "Hën",
    "Mar",
    "Mër",
    "Enj",
    "Pre",
    "Sht",
    "Die",
]
