name = "Czech"
iso_code = "cs"
months = [
    "ledna",
    "února",
    "března",
    "dubna",
    "května",
    "června",
    "července",
    "srpna",
    "září",
    "října",
    "listopadu",
    "prosince",
]
abbr_months = [
    "led",
    "úno",
    "bře",
    "dub",
    "kvě",
    "čen",
    "čec",
    "srp",
    "zář",
    "říj",
    "lis",
    "pro",
]
weekdays = [
    "Pondělí",
    "Úterý",
    "Středa",
    "Čtvrtek",
    "Pátek",
    "Sobota",
    "Neděle",
]
abbr_weekdays = [
    "Po",
    "Út",
    "St",
    "Čt",
    "Pá",
    "So",
    "Ne",
]
