name = "Esperanto"
iso_code = "eo"
months = [
    "Januaro",
    "Februaro",
    "Marto",
    "Aprilo",
    "Majo",
    "Junio",
    "Julio",
    "Aŭgusto",
    "Septembro",
    "Oktobro",
    "Novembro",
    "Decembro",
]
abbr_months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Maj",
    "Jun",
    "Jul",
    "Aŭg",
    "Sep",
    "Okt",
    "Nov",
    "Dec",
]
weekdays = [
    "lundo",
    "mardo",
    "merkredo",
    "ĵaŭdo",
    "vendredo",
    "sabato",
    "dimanĉo",
]
abbr_weekdays = [
    "lun",
    "mar",
    "mer",
    "ĵaŭ",
    "ven",
    "sab",
    "dim",
]
