name = "Finnish"
iso_code = "fi"
months = [
    "tammikuu",
    "helmikuu",
    "maaliskuu",
    "huhtikuu",
    "toukokuu",
    "kes채kuu",
    "hein채kuu",
    "elokuu",
    "syyskuu",
    "lokakuu",
    "marraskuu",
    "joulukuu",
]
abbr_months = [
    "tammi",
    "helmi",
    "maalis",
    "huhti",
    "touko",
    "kes채",
    "hein채",
    "elo",
    "syys",
    "loka",
    "marras",
    "joulu",
]
weekdays = [
    "maanantai",
    "tiistai",
    "keskiviikko",
    "torstai",
    "perjantai",
    "lauantai",
    "sunnuntai",
]
abbr_weekdays = [
    "ma",
    "ti",
    "ke",
    "to",
    "pe",
    "la",
    "su",
]
