name = "Latvian"
iso_code = "lv"
months = [
    "janvāris",
    "februāris",
    "marts",
    "aprīlis",
    "maijs",
    "jūnijs",
    "jūlijs",
    "augusts",
    "septembris",
    "oktobris",
    "novembris",
    "decembris",
]
abbr_months = [
    "jan",
    "feb",
    "mar",
    "apr",
    "mai",
    "jūn",
    "jūl",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
]
weekdays = [
    "pirmdiena",
    "otrdiena",
    "trešdiena",
    "ceturtdiena",
    "piektdiena",
    "sestdiena",
    "svētdiena",
]
abbr_weekdays = [
    "P ",
    "O ",
    "T ",
    "C ",
    "Pk",
    "S ",
    "Sv",
]
