name = "Norwegian Nynorsk"
iso_code = "nn"
months = [
    "januar",
    "februar",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "desember",
]
abbr_months = [
    "jan.",
    "feb.",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "aug.",
    "sep.",
    "okt.",
    "nov.",
    "des.",
]
weekdays = [
    "måndag",
    "tysdag",
    "onsdag",
    "torsdag",
    "fredag",
    "laurdag",
    "sundag",
]
abbr_weekdays = [
    "må.",
    "ty.",
    "on.",
    "to.",
    "fr.",
    "la.",
    "su.",
]
