name = "Norwegian Bokmål"
iso_code = "nb"
months = [
    "januar",
    "februar",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "desember",
]
abbr_months = [
    "jan.",
    "feb.",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "aug.",
    "sep.",
    "okt.",
    "nov.",
    "des.",
]
weekdays = [
    "mandag",
    "tirsdag",
    "onsdag",
    "torsdag",
    "fredag",
    "lørdag",
    "søndag",
]
abbr_weekdays = [
    "ma.",
    "ti.",
    "on.",
    "to.",
    "fr.",
    "lø.",
    "sø.",
]
