name = "Occitan"
iso_code = "oc"
months = [
    "de genièr",
    "de febrièr",
    "de març",
    "d’abrial",
    "de mai",
    "de junh",
    "de julhet",
    "d’agost",
    "de setembre",
    "d’octòbre",
    "de novembre",
    "de decembre",
]
abbr_months = [
    "gen.",
    "febr.",
    "març",
    "abr.",
    "mai",
    "junh",
    "jul.",
    "ago.",
    "set.",
    "oct.",
    "nov.",
    "dec.",
]
weekdays = [
    "diluns",
    "dimars",
    "dimècres",
    "dijóus",
    "divendres",
    "dissabte",
    "dimenge",
]
abbr_weekdays = [
    "dl.",
    "dm.",
    "dc.",
    "dj.",
    "dv.",
    "ds.",
    "dg.",
]
