name = "Romanian"
iso_code = "ro"
months = [
    "ianuarie",
    "februarie",
    "martie",
    "aprilie",
    "mai",
    "iunie",
    "iulie",
    "august",
    "septembrie",
    "octombrie",
    "noiembrie",
    "decembrie",
]
abbr_months = [
    "ian",
    "feb",
    "mar",
    "apr",
    "mai",
    "iun",
    "iul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
]
weekdays = [
    "luni",
    "marți",
    "miercuri",
    "joi",
    "vineri",
    "sâmbătă",
    "duminică",
]
abbr_weekdays = [
    "Lu",
    "Ma",
    "Mi",
    "Jo",
    "Vi",
    "Sb",
    "Du",
]
