name = "Slovak"
iso_code = "sk"
months = [
    "január",
    "február",
    "marec",
    "apríl",
    "máj",
    "jún",
    "júl",
    "august",
    "september",
    "október",
    "november",
    "december",
]
abbr_months = [
    "jan",
    "feb",
    "mar",
    "apr",
    "máj",
    "jún",
    "júl",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
]
weekdays = [
    "Pondelok",
    "Utorok",
    "Streda",
    "Štvrtok",
    "Piatok",
    "Sobota",
    "Nedeľa",
]
abbr_weekdays = [
    "Po",
    "Ut",
    "St",
    "Št",
    "Pi",
    "So",
    "Ne",
]
