name = "Slovenian"
iso_code = "sl"
months = [
    "januar",
    "februar",
    "marec",
    "april",
    "maj",
    "junij",
    "julij",
    "avgust",
    "september",
    "oktober",
    "november",
    "december",
]
abbr_months = [
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "avg",
    "sep",
    "okt",
    "nov",
    "dec",
]
weekdays = [
    "ponedeljek",
    "torek",
    "sreda",
    "četrtek",
    "petek",
    "sobota",
    "nedelja",
]
abbr_weekdays = [
    "pon",
    "tor",
    "sre",
    "čet",
    "pet",
    "sob",
    "ned",
]
