name = "Tagalog"
iso_code = "tl"
months = [
    "Enero",
    "Pebrero",
    "Marso",
    "Abril",
    "Mayo",
    "Hunyo",
    "Hulyo",
    "Agosto",
    "Septiyembre",
    "Oktubre",
    "Nobiyembre",
    "Disyembre",
]
abbr_months = [
    "Ene",
    "Peb",
    "Mar",
    "Abr",
    "May",
    "Hun",
    "Hul",
    "Ago",
    "Sep",
    "Okt",
    "Nob",
    "Dis",
]
weekdays = [
    "Lunes",
    "Martes",
    "Miyerkoles",
    "Huwebes",
    "Biyernes",
    "Sabado",
    "Linggo",
]
abbr_weekdays = [
    "Lun",
    "Mar",
    "Miy",
    "Huw",
    "Biy",
    "Sab",
    "Lin",
]
