name = "Xhosa"
iso_code = "xh"
months = [
    "eyoMqungu",
    "eyoMdumba",
    "eyoKwindla",
    "uTshazimpuzi",
    "uCanzibe",
    "eyeSilimela",
    "eyeKhala",
    "eyeThupa",
    "eyoMsintsi",
    "eyeDwarha",
    "eyeNkanga",
    "eyoMnga",
]
abbr_months = [
    "Mqu",
    "Mdu",
    "Kwi",
    "Tsh",
    "Can",
    "Sil",
    "Kha",
    "Thu",
    "Msi",
    "Dwa",
    "Nka",
    "Mng",
]
weekdays = [
    "uMvulo",
    "lwesiBini",
    "lwesiThathu",
    "ulweSine",
    "lwesiHlanu",
    "uMgqibelo",
    "iCawa",
]
abbr_weekdays = [
    "Mvu",
    "Bin",
    "Tha",
    "Sin",
    "Hla",
    "Mgq",
    "Caw",
]
