name = "Zulu"
iso_code = "zu"
months = [
    "Januwari",
    "Februwari",
    "Mashi",
    "Ephreli",
    "Meyi",
    "Juni",
    "Julayi",
    "Agasti",
    "Septhemba",
    "Okthoba",
    "Novemba",
    "Disemba",
]
abbr_months = [
    "Jan",
    "Feb",
    "Mas",
    "Eph",
    "Mey",
    "Jun",
    "Jul",
    "Aga",
    "Sep",
    "Okt",
    "Nov",
    "Dis",
]
weekdays = [
    "uMsombuluko",
    "uLwesibili",
    "uLwesithathu",
    "uLwesine",
    "uLwesihlanu",
    "uMgqibelo",
    "iSonto",
]
abbr_weekdays = [
    "Mso",
    "Bil",
    "Tha",
    "Sin",
    "Hla",
    "Mgq",
    "Son",
]
