name: Documentation
on:
  push:
    branches:
      - master

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly # needed until rust-lang/rust#43466 lands
          override: true

      - name: Run `cargo doc --all-features`
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

      - name: Build & publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
