name: "Scheduled tasks"

on:
  schedule:
    - cron: "0 0 * * 1,3,5" # midnight on Monday, Wednesday, Friday
  push:
    paths: [".github/workflows/scheduled.yaml"] # build when this file is updated

jobs:
  stale:
    name: Close stale PRs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request has not had any activity recently. It will be closed without further activity."

          days-before-stale: 14
          days-before-close: 7

          stale-pr-label: "C-stale"
          exempt-pr-labels: "C-keep-open"

  security-audit:
    name: Security audit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Audit dependencies
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  check-other-targets:
    name: Type checking
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - { triple: x86_64-unknown-netbsd, has_std: true }
          - { triple: x86_64-sun-solaris, has_std: true }
          - { triple: wasm32-wasi, has_std: true }
          - { triple: thumbv7em-none-eabihf, has_std: false }
          - { triple: x86_64-apple-darwin, has_std: true }
          - { triple: x86_64-fuchsia, has_std: true }
          - { triple: x86_64-linux-android, has_std: true }
          - { triple: x86_64-pc-windows-msvc, has_std: true }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target.triple }}
          override: true

      - name: Install cargo-hack
        shell: bash
        run: |
          curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin

      - name: Cache cargo output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-version_powerset-${{ matrix.target.triple }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Check feature powerset
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: |
            check
            --no-dev-deps
            --version-range 1.40..
            --feature-powerset
            --optional-deps
            --exclude-features default,winapi,std,local-offset,time-macros,quickcheck,quickcheck-dep
            --exclude-all-features
            --target ${{ matrix.target.triple }}
        if: matrix.target.has_std == false

      - name: Check feature powerset
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: |
            check
            --no-dev-deps
            --version-range 1.40..
            --feature-powerset
            --optional-deps
            --exclude-features default,winapi,time-macros,quickcheck-dep
            --target ${{ matrix.target.triple }}
        if: matrix.target.has_std == true
